
export interface ModelAttributes {
    fuel_type?: string;
    series?: string;
    body_group?: string; // critical for service pricing (e.g. G60)
    body_type?: string;
}

const MODEL_MAP: Record<string, ModelAttributes> = {
    '31GE': { fuel_type: 'Petrol', series: 'Seria 1', body_group: 'F70', body_type: 'Hatchback' },
    '11GF': { fuel_type: 'Diesel', series: 'Seria 1', body_group: 'F70', body_type: 'Hatchback' },
    '81GE': { fuel_type: 'Petrol', series: 'Seria 1', body_group: 'F70', body_type: 'Hatchback' },
    '21GF': { fuel_type: 'Diesel', series: 'Seria 1', body_group: 'F70', body_type: 'Hatchback' },
    '61GE': { fuel_type: 'Petrol', series: 'Seria 1', body_group: 'F70', body_type: 'Hatchback' },
    '21GE': { fuel_type: 'Petrol', series: 'Seria 1', body_group: 'F70', body_type: 'Hatchback' },
    '11BX': { fuel_type: 'Petrol', series: 'Seria 2', body_group: 'U06', body_type: 'Hatchback' },
    '21BY': { fuel_type: 'Diesel', series: 'Seria 2', body_group: 'U06', body_type: 'Hatchback' },
    '21BX': { fuel_type: 'Petrol', series: 'Seria 2', body_group: 'U06', body_type: 'Hatchback' },
    '71BY': { fuel_type: 'Diesel', series: 'Seria 2', body_group: 'U06', body_type: 'Hatchback' },
    '71BX': { fuel_type: 'Petrol', series: 'Seria 2', body_group: 'U06', body_type: 'Hatchback' },
    '51BY': { fuel_type: 'Diesel', series: 'Seria 2', body_group: 'U06', body_type: 'Hatchback' },
    '41BX': { fuel_type: 'Petrol', series: 'Seria 2', body_group: 'U06', body_type: 'Hatchback' },
    '21EA': { fuel_type: 'PHEV', series: 'Seria 2', body_group: 'U06', body_type: 'Hatchback' },
    '51BX': { fuel_type: 'PHEV', series: 'Seria 2', body_group: 'U06', body_type: 'Hatchback' },
    '21FL': { fuel_type: 'Diesel', series: 'Seria 5 / i5', body_group: 'G60', body_type: 'Sedan/Limuzyna' },
    '61CM': { fuel_type: 'Petrol', series: 'Seria 2', body_group: 'G42', body_type: 'Coupe' },
    '11CN': { fuel_type: 'Diesel', series: 'Seria 2', body_group: 'G42', body_type: 'Coupe' },
    '11CM': { fuel_type: 'Petrol', series: 'Seria 2', body_group: 'G42', body_type: 'Coupe' },
    '21CM': { fuel_type: 'Petrol', series: 'Seria 2', body_group: 'G42', body_type: 'Coupe' },
    '51FA': { fuel_type: 'Petrol', series: 'Seria 2', body_group: 'G42', body_type: 'Coupe' },
    '41GG': { fuel_type: 'Petrol', series: 'Seria 2', body_group: 'F74', body_type: 'Sedan/Limuzyna' },
    '11GH': { fuel_type: 'Diesel', series: 'Seria 2', body_group: 'F74', body_type: 'Sedan/Limuzyna' },
    '31GH': { fuel_type: 'Petrol', series: 'Seria 2', body_group: 'F74', body_type: 'Sedan/Limuzyna' },
    '21GH': { fuel_type: 'Diesel', series: 'Seria 2', body_group: 'F74', body_type: 'Sedan/Limuzyna' },
    '71GG': { fuel_type: 'Petrol', series: 'Seria 2', body_group: 'F74', body_type: 'Sedan/Limuzyna' },
    '31GG': { fuel_type: 'Petrol', series: 'Seria 2', body_group: 'F74', body_type: 'Sedan/Limuzyna' },
    '31DM': { fuel_type: 'Petrol', series: 'Seria M', body_group: 'G87', body_type: 'Coupe' },
    '21DM': { fuel_type: 'Petrol', series: 'Seria M', body_group: 'G87', body_type: 'Coupe' },
    '31HJ': { fuel_type: 'Petrol', series: 'Seria M', body_group: 'G80', body_type: 'Sedan/Limuzyna' },
    '21HJ': { fuel_type: 'Petrol', series: 'Seria M', body_group: 'G80', body_type: 'Sedan/Limuzyna' },
    '11HJ': { fuel_type: 'Petrol', series: 'Seria M', body_group: 'G80', body_type: 'Sedan/Limuzyna' },
    '31GB': { fuel_type: 'Petrol', series: 'Seria M', body_group: 'G81', body_type: 'Kombi' },
    '21GB': { fuel_type: 'Petrol', series: 'Seria M', body_group: 'G81', body_type: 'Kombi' },
    '28FU': { fuel_type: 'Diesel', series: 'Seria 3', body_group: 'G20', body_type: 'Sedan/Limuzyna' },
    '21FF': { fuel_type: 'Petrol', series: 'Seria 3', body_group: 'G20', body_type: 'Sedan/Limuzyna' },
    '28FF': { fuel_type: 'Petrol', series: 'Seria 3', body_group: 'G20', body_type: 'Sedan/Limuzyna' },
    '38FU': { fuel_type: 'Diesel', series: 'Seria 3', body_group: 'G20', body_type: 'Sedan/Limuzyna' },
    '41FU': { fuel_type: 'Diesel', series: 'Seria 3', body_group: 'G20', body_type: 'Sedan/Limuzyna' },
    '48FU': { fuel_type: 'Diesel', series: 'Seria 3', body_group: 'G20', body_type: 'Sedan/Limuzyna' },
    '58FF': { fuel_type: 'Petrol', series: 'Seria 3', body_group: 'G20', body_type: 'Sedan/Limuzyna' },
    '78FF': { fuel_type: 'Petrol', series: 'Seria 3', body_group: 'G20', body_type: 'Sedan/Limuzyna' },
    '71FF': { fuel_type: 'Petrol', series: 'Seria 3', body_group: 'G20', body_type: 'Sedan/Limuzyna' },
    '58FU': { fuel_type: 'Diesel', series: 'Seria 3', body_group: 'G20', body_type: 'Sedan/Limuzyna' },
    '51FU': { fuel_type: 'Diesel', series: 'Seria 3', body_group: 'G20', body_type: 'Sedan/Limuzyna' },
    '41GK': { fuel_type: 'PHEV', series: 'Seria 3', body_group: 'G20', body_type: 'Sedan/Limuzyna' },
    '48GK': { fuel_type: 'PHEV', series: 'Seria 3', body_group: 'G20', body_type: 'Sedan/Limuzyna' },
    '51GK': { fuel_type: 'PHEV', series: 'Seria 3', body_group: 'G20', body_type: 'Sedan/Limuzyna' },
    '58GK': { fuel_type: 'PHEV', series: 'Seria 3', body_group: 'G20', body_type: 'Sedan/Limuzyna' },
    '88FF': { fuel_type: 'Petrol', series: 'Seria 3', body_group: 'G20', body_type: 'Sedan/Limuzyna' },
    '81FF': { fuel_type: 'Petrol', series: 'Seria 3', body_group: 'G20', body_type: 'Sedan/Limuzyna' },
    '68FU': { fuel_type: 'Diesel', series: 'Seria 3', body_group: 'G20', body_type: 'Sedan/Limuzyna' },
    '61FU': { fuel_type: 'Diesel', series: 'Seria 3', body_group: 'G20', body_type: 'Sedan/Limuzyna' },
    '61FT': { fuel_type: 'Petrol', series: 'Seria 3', body_group: 'G20', body_type: 'Sedan/Limuzyna' },
    '68FT': { fuel_type: 'Petrol', series: 'Seria 3', body_group: 'G20', body_type: 'Sedan/Limuzyna' },
    '11FZ': { fuel_type: 'Diesel', series: 'Seria 3', body_group: 'G21', body_type: 'Kombi' },
    '11FY': { fuel_type: 'Petrol', series: 'Seria 3', body_group: 'G21', body_type: 'Kombi' },
    '21FZ': { fuel_type: 'Diesel', series: 'Seria 3', body_group: 'G21', body_type: 'Kombi' },
    '31FZ': { fuel_type: 'Diesel', series: 'Seria 3', body_group: 'G21', body_type: 'Kombi' },
    '21FY': { fuel_type: 'Petrol', series: 'Seria 3', body_group: 'G21', body_type: 'Kombi' },
    '51FZ': { fuel_type: 'Diesel', series: 'Seria 3', body_group: 'G21', body_type: 'Kombi' },
    '41GL': { fuel_type: 'PHEV', series: 'Seria 3', body_group: 'G21', body_type: 'Kombi' },
    '51GL': { fuel_type: 'PHEV', series: 'Seria 3', body_group: 'G21', body_type: 'Kombi' },
    '71FY': { fuel_type: 'Petrol', series: 'Seria 3', body_group: 'G21', body_type: 'Kombi' },
    '61FZ': { fuel_type: 'Diesel', series: 'Seria 3', body_group: 'G21', body_type: 'Kombi' },
    '21GL': { fuel_type: 'Petrol', series: 'Seria 3', body_group: 'G21', body_type: 'Kombi' },
    '41BA': { fuel_type: 'Petrol', series: 'Seria M', body_group: 'G83', body_type: 'Cabrio' },
    '21HK': { fuel_type: 'Petrol', series: 'Seria M', body_group: 'G82', body_type: 'Coupe' },
    '31HK': { fuel_type: 'Petrol', series: 'Seria M', body_group: 'G82', body_type: 'Coupe' },
    '11HK': { fuel_type: 'Petrol', series: 'Seria M', body_group: 'G82', body_type: 'Coupe' },
    '51AU': { fuel_type: 'Diesel', series: 'Seria 4 / i4', body_group: 'G23', body_type: 'Cabrio' },
    '81DB': { fuel_type: 'Petrol', series: 'Seria 4 / i4', body_group: 'G23', body_type: 'Cabrio' },
    '61AU': { fuel_type: 'Diesel', series: 'Seria 4 / i4', body_group: 'G23', body_type: 'Cabrio' },
    '41FP': { fuel_type: 'Petrol', series: 'Seria 4 / i4', body_group: 'G23', body_type: 'Cabrio' },
    '71AU': { fuel_type: 'Diesel', series: 'Seria 4 / i4', body_group: 'G23', body_type: 'Cabrio' },
    '71DB': { fuel_type: 'Petrol', series: 'Seria 4 / i4', body_group: 'G23', body_type: 'Cabrio' },
    '41FN': { fuel_type: 'Diesel', series: 'Seria 4 / i4', body_group: 'G22', body_type: 'Coupe' },
    '51FN': { fuel_type: 'Diesel', series: 'Seria 4 / i4', body_group: 'G22', body_type: 'Coupe' },
    '11HB': { fuel_type: 'Petrol', series: 'Seria 4 / i4', body_group: 'G22', body_type: 'Coupe' },
    '61FN': { fuel_type: 'Diesel', series: 'Seria 4 / i4', body_group: 'G22', body_type: 'Coupe' },
    '51HB': { fuel_type: 'Petrol', series: 'Seria 4 / i4', body_group: 'G22', body_type: 'Coupe' },
    '71FN': { fuel_type: 'Diesel', series: 'Seria 4 / i4', body_group: 'G22', body_type: 'Coupe' },
    '81DA': { fuel_type: 'Petrol', series: 'Seria 4 / i4', body_group: 'G22', body_type: 'Coupe' },
    '41FR': { fuel_type: 'Diesel', series: 'Seria 4 / i4', body_group: 'G26', body_type: 'Sedan/Limuzyna' },
    '51FR': { fuel_type: 'Diesel', series: 'Seria 4 / i4', body_group: 'G26', body_type: 'Sedan/Limuzyna' },
    '11HC': { fuel_type: 'Petrol', series: 'Seria 4 / i4', body_group: 'G26', body_type: 'Sedan/Limuzyna' },
    '61FR': { fuel_type: 'Diesel', series: 'Seria 4 / i4', body_group: 'G26', body_type: 'Sedan/Limuzyna' },
    '41HC': { fuel_type: 'Petrol', series: 'Seria 4 / i4', body_group: 'G26', body_type: 'Sedan/Limuzyna' },
    '61FB': { fuel_type: 'Petrol', series: 'Seria 4 / i4', body_group: 'G26', body_type: 'Sedan/Limuzyna' },
    '71HD': { fuel_type: 'BEV', series: 'Seria 4 / i4', body_group: 'G26', body_type: 'Sedan/Limuzyna' },
    '51HD': { fuel_type: 'BEV', series: 'Seria 4 / i4', body_group: 'G26', body_type: 'Sedan/Limuzyna' },
    '61HD': { fuel_type: 'BEV', series: 'Seria 4 / i4', body_group: 'G26', body_type: 'Sedan/Limuzyna' },
    '41HD': { fuel_type: 'BEV', series: 'Seria 4 / i4', body_group: 'G26', body_type: 'Sedan/Limuzyna' },
    '11FL': { fuel_type: 'Diesel', series: 'Seria 5 / i5', body_group: 'G60', body_type: 'Sedan/Limuzyna' },
    '11FJ': { fuel_type: 'Petrol', series: 'Seria 5 / i5', body_group: 'G60', body_type: 'Sedan/Limuzyna' },
    '71FJ': { fuel_type: 'PHEV', series: 'Seria 5 / i5', body_group: 'G60', body_type: 'Sedan/Limuzyna' },
    '81FJ': { fuel_type: 'PHEV', series: 'Seria 5 / i5', body_group: 'G60', body_type: 'Sedan/Limuzyna' },
    '31FL': { fuel_type: 'Diesel', series: 'Seria 5 / i5', body_group: 'G60', body_type: 'Sedan/Limuzyna' },
    '11FK': { fuel_type: 'PHEV', series: 'Seria 5 / i5', body_group: 'G60', body_type: 'Sedan/Limuzyna' },
    '41HG': { fuel_type: 'BEV', series: 'Seria 5 / i5', body_group: 'G60', body_type: 'Sedan/Limuzyna' },
    '61HG': { fuel_type: 'BEV', series: 'Seria 5 / i5', body_group: 'G60', body_type: 'Sedan/Limuzyna' },
    '31HG': { fuel_type: 'BEV', series: 'Seria 5 / i5', body_group: 'G60', body_type: 'Sedan/Limuzyna' },
    '11GW': { fuel_type: 'Diesel', series: 'Seria 5 / i5', body_group: 'G61', body_type: 'Kombi' },
    '21GW': { fuel_type: 'Diesel', series: 'Seria 5 / i5', body_group: 'G61', body_type: 'Kombi' },
    '11GV': { fuel_type: 'Petrol', series: 'Seria 5 / i5', body_group: 'G61', body_type: 'Kombi' },
    '21GV': { fuel_type: 'PHEV', series: 'Seria 5 / i5', body_group: 'G61', body_type: 'Kombi' },
    '31GV': { fuel_type: 'PHEV', series: 'Seria 5 / i5', body_group: 'G61', body_type: 'Kombi' },
    '31GW': { fuel_type: 'Diesel', series: 'Seria 5 / i5', body_group: 'G61', body_type: 'Kombi' },
    '41GV': { fuel_type: 'PHEV', series: 'Seria 5 / i5', body_group: 'G61', body_type: 'Kombi' },
    '61HH': { fuel_type: 'BEV', series: 'Seria 5 / i5', body_group: 'G61', body_type: 'Kombi' },
    '71HH': { fuel_type: 'BEV', series: 'Seria 5 / i5', body_group: 'G61', body_type: 'Kombi' },
    '51HH': { fuel_type: 'BEV', series: 'Seria 5 / i5', body_group: 'G61', body_type: 'Kombi' },
    '81FK': { fuel_type: 'PHEV', series: 'Seria M', body_group: 'G90', body_type: 'Sedan/Limuzyna' },
    '81GV': { fuel_type: 'PHEV', series: 'Seria M', body_group: 'G99', body_type: 'Kombi' },
    '21EJ': { fuel_type: 'Diesel', series: 'Seria 7 / i7', body_group: 'G70', body_type: 'Sedan/Limuzyna' },
    '41EH': { fuel_type: 'PHEV', series: 'Seria 7 / i7', body_group: 'G70', body_type: 'Sedan/Limuzyna' },
    '51EH': { fuel_type: 'PHEV', series: 'Seria 7 / i7', body_group: 'G70', body_type: 'Sedan/Limuzyna' },
    '81EH': { fuel_type: 'BEV', series: 'Seria 7 / i7', body_group: 'G70', body_type: 'Sedan/Limuzyna' },
    '41EJ': { fuel_type: 'BEV', series: 'Seria 7 / i7', body_group: 'G70', body_type: 'Sedan/Limuzyna' },
    '51EJ': { fuel_type: 'BEV', series: 'Seria 7 / i7', body_group: 'G70', body_type: 'Sedan/Limuzyna' },
    '11EF': { fuel_type: 'Petrol', series: 'X1 / iX1', body_group: 'U11', body_type: 'SUV/Crossover' },
    '11EG': { fuel_type: 'Diesel', series: 'X1 / iX1', body_group: 'U11', body_type: 'SUV/Crossover' },
    '11EE': { fuel_type: 'Petrol', series: 'X1 / iX1', body_group: 'U11', body_type: 'SUV/Crossover' },
    '31EG': { fuel_type: 'Diesel', series: 'X1 / iX1', body_group: 'U11', body_type: 'SUV/Crossover' },
    '31EE': { fuel_type: 'Petrol', series: 'X1 / iX1', body_group: 'U11', body_type: 'SUV/Crossover' },
    '41EG': { fuel_type: 'Diesel', series: 'X1 / iX1', body_group: 'U11', body_type: 'SUV/Crossover' },
    '51EG': { fuel_type: 'Diesel', series: 'X1 / iX1', body_group: 'U11', body_type: 'SUV/Crossover' },
    '61EE': { fuel_type: 'Petrol', series: 'X1 / iX1', body_group: 'U11', body_type: 'SUV/Crossover' },
    '21EF': { fuel_type: 'PHEV', series: 'X1 / iX1', body_group: 'U11', body_type: 'SUV/Crossover' },
    '31EF': { fuel_type: 'PHEV', series: 'X1 / iX1', body_group: 'U11', body_type: 'SUV/Crossover' },
    '71EG': { fuel_type: 'BEV', series: 'X1 / iX1', body_group: 'U11', body_type: 'SUV/Crossover' },
    '61EF': { fuel_type: 'BEV', series: 'X1 / iX1', body_group: 'U11', body_type: 'SUV/Crossover' },
    '81GM': { fuel_type: 'Petrol', series: 'X2 / iX2', body_group: 'U10', body_type: 'SUV/Crossover' },
    '31GN': { fuel_type: 'Diesel', series: 'X2 / iX2', body_group: 'U10', body_type: 'SUV/Crossover' },
    '41GN': { fuel_type: 'Diesel', series: 'X2 / iX2', body_group: 'U10', body_type: 'SUV/Crossover' },
    '21GM': { fuel_type: 'Petrol', series: 'X2 / iX2', body_group: 'U10', body_type: 'SUV/Crossover' },
    '51GM': { fuel_type: 'BEV', series: 'X2 / iX2', body_group: 'U10', body_type: 'SUV/Crossover' },
    '71GM': { fuel_type: 'BEV', series: 'X2 / iX2', body_group: 'U10', body_type: 'SUV/Crossover' },
    '31GP': { fuel_type: 'Petrol', series: 'X3 / iX3', body_group: 'G45', body_type: 'SUV/Crossover' },
    '35GP': { fuel_type: 'Petrol', series: 'X3 / iX3', body_group: 'G45', body_type: 'SUV/Crossover' },
    '11GR': { fuel_type: 'Diesel', series: 'X3 / iX3', body_group: 'G45', body_type: 'SUV/Crossover' },
    '15GR': { fuel_type: 'Diesel', series: 'X3 / iX3', body_group: 'G45', body_type: 'SUV/Crossover' },
    '65GP': { fuel_type: 'PHEV', series: 'X3 / iX3', body_group: 'G45', body_type: 'SUV/Crossover' },
    '25GR': { fuel_type: 'Diesel', series: 'X3 / iX3', body_group: 'G45', body_type: 'SUV/Crossover' },
    '71GP': { fuel_type: 'Petrol', series: 'X3 / iX3', body_group: 'G45', body_type: 'SUV/Crossover' },
    '31EU': { fuel_type: 'Petrol', series: 'X5', body_group: 'G05', body_type: 'SUV/Crossover' },
    '11EV': { fuel_type: 'Diesel', series: 'X5', body_group: 'G05', body_type: 'SUV/Crossover' },
    '21EV': { fuel_type: 'Diesel', series: 'X5', body_group: 'G05', body_type: 'SUV/Crossover' },
    '21EU': { fuel_type: 'Petrol', series: 'X5', body_group: 'G05', body_type: 'SUV/Crossover' },
    '41EU': { fuel_type: 'PHEV', series: 'X5', body_group: 'G05', body_type: 'SUV/Crossover' },
    '11ET': { fuel_type: 'Petrol', series: 'Seria M', body_group: 'F95', body_type: 'SUV/Crossover' },
    '41EX': { fuel_type: 'Petrol', series: 'X6', body_group: 'G06', body_type: 'SUV/Crossover' },
    '11EY': { fuel_type: 'Diesel', series: 'X6', body_group: 'G06', body_type: 'SUV/Crossover' },
    '21EY': { fuel_type: 'Diesel', series: 'X6', body_group: 'G06', body_type: 'SUV/Crossover' },
    '31EX': { fuel_type: 'Petrol', series: 'X6', body_group: 'G06', body_type: 'SUV/Crossover' },
    '21ET': { fuel_type: 'Petrol', series: 'Seria M', body_group: 'F96', body_type: 'SUV/Crossover' },
    '31EM': { fuel_type: 'Petrol', series: 'X7', body_group: 'G07', body_type: 'SUV/Crossover' },
    '21EN': { fuel_type: 'Diesel', series: 'X7', body_group: 'G07', body_type: 'SUV/Crossover' },
    '21EM': { fuel_type: 'Petrol', series: 'X7', body_group: 'G07', body_type: 'SUV/Crossover' },
    '11CS': { fuel_type: 'PHEV', series: 'Seria M', body_group: 'G09', body_type: 'SUV/Crossover' },
    '31CS': { fuel_type: 'PHEV', series: 'Seria M', body_group: 'G09', body_type: 'SUV/Crossover' },
    '31HR': { fuel_type: 'BEV', series: 'X3 / iX3', body_group: 'NA5', body_type: 'SUV/Crossover' },
    'HF51': { fuel_type: 'Petrol', series: 'Seria Z', body_group: 'G29', body_type: 'Cabrio' },
    'HF11': { fuel_type: 'Petrol', series: 'Seria Z', body_group: 'G29', body_type: 'Cabrio' },
    'HF31': { fuel_type: 'Petrol', series: 'Seria Z', body_group: 'G29', body_type: 'Cabrio' },
    '61CF': { fuel_type: 'BEV', series: 'iX', body_group: 'i20', body_type: 'SUV/Crossover' },
    '41CF': { fuel_type: 'BEV', series: 'iX', body_group: 'i20', body_type: 'SUV/Crossover' },
    '51CF': { fuel_type: 'BEV', series: 'iX', body_group: 'i20', body_type: 'SUV/Crossover' },
};

export function getModelAttributes(code: string): ModelAttributes {
    return MODEL_MAP[code] || {};
}
