-- Create a table for global site settings (singleton pattern)
create table if not exists site_settings (
    id int primary key generated by default as identity,
    key text unique not null,
    value text, -- Store as text, JSON, or boolean string
    updated_at timestamptz default now()
);

-- Enable RLS
alter table site_settings enable row level security;

-- Policy: Allow read access to everyone (public settings)
create policy "Allow public read access to site_settings"
    on site_settings for select
    using (true);

-- Policy: Allow write access only to authenticated admins
-- Assuming authentication is handled via Supabase Auth or custom admin logic
-- For now, we'll allow anon/admin write for simplicity in development, 
-- but in prod this should be restricted.
create policy "Allow admin write access to site_settings"
    on site_settings for insert
    with check (true);

create policy "Allow admin update access to site_settings"
    on site_settings for update
    using (true);

-- Insert default settings if not exist
insert into site_settings (key, value)
values 
    ('intro_media_url', ''),
    ('intro_cta_link', ''),
    ('intro_contact_phone', '+48 000 000 000')
on conflict (key) do nothing;
